[package]
name = "touchstone"
version = "0.1.0"
authors = ["Mark Wong <mark@2ndQuadrant.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
